  
  # From BIGSMALL
  DATA:
    FS: 30
    DATASET: Neckflix
    DO_PREPROCESS: True              # if first time, should be true
    DATA_FORMAT: NDCHW    # Frames, Channels, Height, Width
    DATA_PATH:  "" 
    CACHED_PATH: ""  # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    # Fold is used for bigsmall referring to cross-fold validation
    FOLD:
      FOLD_NAME: ''
      FOLD_PATH: ''
    # Begin and End are used for when training on this dataset and testing on another dataset
    BEGIN: 0.0
    END: 0.6
    PREPROCESS:
      DATA_TYPE: ['Raw']    # 'Raw' or 'DiffNormalized' is supported
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      USE_PSUEDO_PPG_LABEL: True
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 3 # chunk length
      USE_BIGSMALL: False
      BIGSMALL:
        BIG_DATA_TYPE: ['Standardized']
        SMALL_DATA_TYPE: ['DiffNormalized']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9
      NECKFLIX:
        CameraMode: RGB # RGB, RGBI, RGBD, RGBBID, I, ID, D, EV
        StereoMode: False # Not yet implemented
      RESIZE:
        H: 72
        W: 72

# From iBVP
  DATA:
    PREPROCESS: 
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used

